### ISSUE TITLE
Bisection

### ISSUE THREAD

**Issue by erikbozik** [spitalskya/MVO-Solvency-LogReg#10]
- [x] - implement
- [ ] - test

**Comment by teoPazera** [comment]
- [x] change the way interval is created to be exponential

**Comment by teoPazera** [comment]
- [x] FIX calculated gradient too many times

**Comment by spitalskya** [comment]
- [x] `approx_fprime` nemá parameter `args`, treba `*args` (`lambda x: approx_fprime(x, obj_fun, args=args)`)
