### ISSUE TITLE
Clean-up of methods

### ISSUE THREAD

**Issue by spitalskya** [spitalskya/MVO-Solvency-LogReg#14]
Each minimization method should contain:
- [x] `args`, `kwargs` -> `options` and `callback` parameters
- [x] proper documentation
- [x] can handle functions with `args`
- [x] `grad` wrapped in `typing.Optional`
- [x] `str` method arguments change to `Literal[...]`
- [x] method NEED to have unified arguments (ANDREJ!!!)

**Comment by teoPazera** [comment]
- [x] aproximate gradient everywhere if there is none
```
if grad is None:
        def grad(x: np.ndarray, *args) -> np.ndarray:
            return approx_fprime(x, obj_fun, *args)
```

**Comment by teoPazera** [comment]
- [ ] Callable -> to callable

**Comment by teoPazera** [comment]
- [x] annotations everywhere
- [x] 10e-3 -> 1e-3
- [ ] trajectory: np.array[np.array]
- [x] matica type hint np.array[np.array]
