### ISSUE TITLE
Backtracking

### ISSUE THREAD

**Issue by erikbozik** [spitalskya/MVO-Solvency-LogReg#9]
- [x] - implement
- [ ] - test

**Comment by teoPazera** [comment]
- [ ] backtracking check if backtracking can end badly
- [x] return nfev, njev

**Comment by spitalskya** [comment]
- [x] `approx_fprime` nemá parameter `args`, treba `*args` (`lambda x: approx_fprime(x, obj_fun, args=args)`)
